// Generated by Haxe 4.3.1
#include <hxcpp.h>

#ifndef INCLUDED_hx_widgets_DataObject
#include <hx/widgets/DataObject.h>
#endif
#ifndef INCLUDED_hx_widgets_DataObjectSimple
#include <hx/widgets/DataObjectSimple.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_7c18c34b848061ce_3_new,"hx.widgets.DataObjectSimple","new",0xd8905aea,"hx.widgets.DataObjectSimple.new","hx/widgets/DataObjectSimple.hx",3,0x34a37004)
namespace hx{
namespace widgets{

void DataObjectSimple_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_7c18c34b848061ce_3_new)
HXDLIN(   3)		super::__construct();
            	}

Dynamic DataObjectSimple_obj::__CreateEmpty() { return new DataObjectSimple_obj; }

void *DataObjectSimple_obj::_hx_vtable = 0;

Dynamic DataObjectSimple_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< DataObjectSimple_obj > _hx_result = new DataObjectSimple_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool DataObjectSimple_obj::_hx_isInstanceOf(int inClassId) {
	if (inClassId<=(int)0x30b2a788) {
		return inClassId==(int)0x00000001 || inClassId==(int)0x30b2a788;
	} else {
		return inClassId==(int)0x472475da;
	}
}


::hx::ObjectPtr< DataObjectSimple_obj > DataObjectSimple_obj::__new() {
	::hx::ObjectPtr< DataObjectSimple_obj > __this = new DataObjectSimple_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< DataObjectSimple_obj > DataObjectSimple_obj::__alloc(::hx::Ctx *_hx_ctx) {
	DataObjectSimple_obj *__this = (DataObjectSimple_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(DataObjectSimple_obj), true, "hx.widgets.DataObjectSimple"));
	*(void **)__this = DataObjectSimple_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

DataObjectSimple_obj::DataObjectSimple_obj()
{
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *DataObjectSimple_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *DataObjectSimple_obj_sStaticStorageInfo = 0;
#endif

::hx::Class DataObjectSimple_obj::__mClass;

void DataObjectSimple_obj::__register()
{
	DataObjectSimple_obj _hx_dummy;
	DataObjectSimple_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("hx.widgets.DataObjectSimple",f8,5d,82,c1);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< DataObjectSimple_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = DataObjectSimple_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = DataObjectSimple_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace hx
} // end namespace widgets
