// Generated by Haxe 4.3.1
#include <hxcpp.h>

#ifndef INCLUDED_EReg
#include <EReg.h>
#endif
#ifndef INCLUDED_haxe_ui_backend_ComponentBase
#include <haxe/ui/backend/ComponentBase.h>
#endif
#ifndef INCLUDED_haxe_ui_backend_ComponentImpl
#include <haxe/ui/backend/ComponentImpl.h>
#endif
#ifndef INCLUDED_haxe_ui_backend_ComponentSurface
#include <haxe/ui/backend/ComponentSurface.h>
#endif
#ifndef INCLUDED_haxe_ui_backend_TextBase
#include <haxe/ui/backend/TextBase.h>
#endif
#ifndef INCLUDED_haxe_ui_backend_TextDisplayImpl
#include <haxe/ui/backend/TextDisplayImpl.h>
#endif
#ifndef INCLUDED_haxe_ui_backend_TextInputImpl
#include <haxe/ui/backend/TextInputImpl.h>
#endif
#ifndef INCLUDED_haxe_ui_behaviours_Behaviour
#include <haxe/ui/behaviours/Behaviour.h>
#endif
#ifndef INCLUDED_haxe_ui_behaviours_Behaviours
#include <haxe/ui/behaviours/Behaviours.h>
#endif
#ifndef INCLUDED_haxe_ui_behaviours_DataBehaviour
#include <haxe/ui/behaviours/DataBehaviour.h>
#endif
#ifndef INCLUDED_haxe_ui_behaviours_IValidatingBehaviour
#include <haxe/ui/behaviours/IValidatingBehaviour.h>
#endif
#ifndef INCLUDED_haxe_ui_behaviours_ValueBehaviour
#include <haxe/ui/behaviours/ValueBehaviour.h>
#endif
#ifndef INCLUDED_haxe_ui_components_TextField
#include <haxe/ui/components/TextField.h>
#endif
#ifndef INCLUDED_haxe_ui_components__TextField_PasswordBehaviour
#include <haxe/ui/components/_TextField/PasswordBehaviour.h>
#endif
#ifndef INCLUDED_haxe_ui_components__TextField_RestrictCharsBehaviour
#include <haxe/ui/components/_TextField/RestrictCharsBehaviour.h>
#endif
#ifndef INCLUDED_haxe_ui_components__TextField_TextFieldHelper
#include <haxe/ui/components/_TextField/TextFieldHelper.h>
#endif
#ifndef INCLUDED_haxe_ui_core_Component
#include <haxe/ui/core/Component.h>
#endif
#ifndef INCLUDED_haxe_ui_core_ComponentBounds
#include <haxe/ui/core/ComponentBounds.h>
#endif
#ifndef INCLUDED_haxe_ui_core_ComponentCommon
#include <haxe/ui/core/ComponentCommon.h>
#endif
#ifndef INCLUDED_haxe_ui_core_ComponentContainer
#include <haxe/ui/core/ComponentContainer.h>
#endif
#ifndef INCLUDED_haxe_ui_core_ComponentEvents
#include <haxe/ui/core/ComponentEvents.h>
#endif
#ifndef INCLUDED_haxe_ui_core_ComponentLayout
#include <haxe/ui/core/ComponentLayout.h>
#endif
#ifndef INCLUDED_haxe_ui_core_ComponentValidation
#include <haxe/ui/core/ComponentValidation.h>
#endif
#ifndef INCLUDED_haxe_ui_core_IClonable
#include <haxe/ui/core/IClonable.h>
#endif
#ifndef INCLUDED_haxe_ui_core_IValueComponent
#include <haxe/ui/core/IValueComponent.h>
#endif
#ifndef INCLUDED_haxe_ui_core_InteractiveComponent
#include <haxe/ui/core/InteractiveComponent.h>
#endif
#ifndef INCLUDED_haxe_ui_core_TextInput
#include <haxe/ui/core/TextInput.h>
#endif
#ifndef INCLUDED_haxe_ui_focus_IFocusable
#include <haxe/ui/focus/IFocusable.h>
#endif
#ifndef INCLUDED_haxe_ui_layouts_ILayout
#include <haxe/ui/layouts/ILayout.h>
#endif
#ifndef INCLUDED_haxe_ui_layouts_Layout
#include <haxe/ui/layouts/Layout.h>
#endif
#ifndef INCLUDED_haxe_ui_util_VariantType
#include <haxe/ui/util/VariantType.h>
#endif
#ifndef INCLUDED_haxe_ui_util__Variant_Variant_Impl_
#include <haxe/ui/util/_Variant/Variant_Impl_.h>
#endif
#ifndef INCLUDED_haxe_ui_validation_IValidating
#include <haxe/ui/validation/IValidating.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_2c750dafee1aa8d4_321_validateText,"haxe.ui.components._TextField.TextFieldHelper","validateText",0x5bfa66f0,"haxe.ui.components._TextField.TextFieldHelper.validateText","haxe/ui/components/TextField.hx",321,0x9dfe9498)
HX_LOCAL_STACK_FRAME(_hx_pos_2c750dafee1aa8d4_364_validateHtmlText,"haxe.ui.components._TextField.TextFieldHelper","validateHtmlText",0xe866977b,"haxe.ui.components._TextField.TextFieldHelper.validateHtmlText","haxe/ui/components/TextField.hx",364,0x9dfe9498)
namespace haxe{
namespace ui{
namespace components{
namespace _TextField{

void TextFieldHelper_obj::__construct() { }

Dynamic TextFieldHelper_obj::__CreateEmpty() { return new TextFieldHelper_obj; }

void *TextFieldHelper_obj::_hx_vtable = 0;

Dynamic TextFieldHelper_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< TextFieldHelper_obj > _hx_result = new TextFieldHelper_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool TextFieldHelper_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7ca7dad1;
}

void TextFieldHelper_obj::validateText( ::haxe::ui::components::TextField textfield,::String text){
            	HX_STACKFRAME(&_hx_pos_2c750dafee1aa8d4_321_validateText)
HXLINE( 322)		if (::hx::IsNull( text )) {
HXLINE( 323)			text = HX_("",00,00,00,00);
            		}
HXLINE( 326)		bool placeholderVisible = (text.length == 0);
HXLINE( 327)		 ::haxe::ui::util::VariantType password = ::hx::TCast<  ::haxe::ui::components::_TextField::PasswordBehaviour >::cast(textfield->behaviours->find(HX_("password",1b,23,d0,48),null()))->originalValue;
HXLINE( 328)		 ::EReg regexp = ::hx::TCast<  ::haxe::ui::components::_TextField::RestrictCharsBehaviour >::cast(textfield->behaviours->find(HX_("restrictChars",01,08,2c,ba),null()))->regexp;
HXLINE( 330)		bool _hx_tmp;
HXDLIN( 330)		bool _hx_tmp1;
HXDLIN( 330)		if ((textfield->get_maxChars() > 0)) {
HXLINE( 330)			int text1 = text.length;
HXDLIN( 330)			_hx_tmp1 = (text1 > textfield->get_maxChars());
            		}
            		else {
HXLINE( 330)			_hx_tmp1 = false;
            		}
HXDLIN( 330)		if (_hx_tmp1) {
HXLINE( 330)			_hx_tmp = (placeholderVisible == false);
            		}
            		else {
HXLINE( 330)			_hx_tmp = false;
            		}
HXDLIN( 330)		if (_hx_tmp) {
HXLINE( 331)			text = text.substr(0,textfield->get_maxChars());
            		}
HXLINE( 334)		if (::hx::IsNotNull( regexp )) {
HXLINE( 335)			text = regexp->replace(text,HX_("",00,00,00,00));
            		}
HXLINE( 338)		if (::hx::IsNotNull( textfield->get_placeholder() )) {
HXLINE( 339)			if ((textfield->get_focus() == false)) {
HXLINE( 340)				if ((text.length == 0)) {
HXLINE( 341)					text = textfield->get_placeholder();
HXLINE( 342)					textfield->set_password(false);
HXLINE( 343)					textfield->addClass(HX_(":empty",13,28,8d,a0),null(),null());
            				}
            				else {
HXLINE( 344)					if ((text != textfield->get_placeholder())) {
HXLINE( 345)						textfield->set_password(::haxe::ui::util::_Variant::Variant_Impl__obj::toBool(password));
HXLINE( 346)						textfield->removeClass(HX_(":empty",13,28,8d,a0),null(),null());
            					}
            				}
            			}
            			else {
HXLINE( 349)				textfield->removeClass(HX_(":empty",13,28,8d,a0),null(),null());
HXLINE( 350)				textfield->set_password(::haxe::ui::util::_Variant::Variant_Impl__obj::toBool(password));
            			}
            		}
            		else {
HXLINE( 353)			textfield->set_password(::haxe::ui::util::_Variant::Variant_Impl__obj::toBool(password));
HXLINE( 355)			if ((placeholderVisible == true)) {
HXLINE( 356)				textfield->removeClass(HX_(":empty",13,28,8d,a0),null(),null());
            			}
            		}
HXLINE( 360)		textfield->getTextInput()->set_text((HX_("",00,00,00,00) + text));
HXLINE( 361)		{
HXLINE( 361)			bool _hx_tmp2;
HXDLIN( 361)			if (::hx::IsNotNull( textfield->_layout )) {
HXLINE( 361)				_hx_tmp2 = (textfield->_layoutLocked == true);
            			}
            			else {
HXLINE( 361)				_hx_tmp2 = true;
            			}
HXDLIN( 361)			if (!(_hx_tmp2)) {
HXLINE( 361)				textfield->invalidateComponent(HX_("layout",aa,ae,b8,58),false);
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(TextFieldHelper_obj,validateText,(void))

void TextFieldHelper_obj::validateHtmlText( ::haxe::ui::components::TextField textfield,::String htmlText){
            	HX_STACKFRAME(&_hx_pos_2c750dafee1aa8d4_364_validateHtmlText)
HXLINE( 365)		if (::hx::IsNull( htmlText )) {
HXLINE( 366)			htmlText = HX_("",00,00,00,00);
            		}
HXLINE( 369)		bool placeholderVisible = (htmlText.length == 0);
HXLINE( 370)		 ::haxe::ui::util::VariantType password = ::hx::TCast<  ::haxe::ui::components::_TextField::PasswordBehaviour >::cast(textfield->behaviours->find(HX_("password",1b,23,d0,48),null()))->originalValue;
HXLINE( 371)		 ::EReg regexp = ::hx::TCast<  ::haxe::ui::components::_TextField::RestrictCharsBehaviour >::cast(textfield->behaviours->find(HX_("restrictChars",01,08,2c,ba),null()))->regexp;
HXLINE( 373)		bool _hx_tmp;
HXDLIN( 373)		bool _hx_tmp1;
HXDLIN( 373)		if ((textfield->get_maxChars() > 0)) {
HXLINE( 373)			int htmlText1 = htmlText.length;
HXDLIN( 373)			_hx_tmp1 = (htmlText1 > textfield->get_maxChars());
            		}
            		else {
HXLINE( 373)			_hx_tmp1 = false;
            		}
HXDLIN( 373)		if (_hx_tmp1) {
HXLINE( 373)			_hx_tmp = (placeholderVisible == false);
            		}
            		else {
HXLINE( 373)			_hx_tmp = false;
            		}
HXDLIN( 373)		if (_hx_tmp) {
HXLINE( 374)			htmlText = htmlText.substr(0,textfield->get_maxChars());
            		}
HXLINE( 377)		if (::hx::IsNotNull( regexp )) {
HXLINE( 378)			htmlText = regexp->replace(htmlText,HX_("",00,00,00,00));
            		}
HXLINE( 381)		if (::hx::IsNotNull( textfield->get_placeholder() )) {
HXLINE( 382)			if ((textfield->get_focus() == false)) {
HXLINE( 383)				if ((htmlText.length == 0)) {
HXLINE( 384)					htmlText = textfield->get_placeholder();
HXLINE( 385)					textfield->set_password(false);
HXLINE( 386)					textfield->addClass(HX_(":empty",13,28,8d,a0),null(),null());
            				}
            				else {
HXLINE( 387)					if ((htmlText != textfield->get_placeholder())) {
HXLINE( 388)						textfield->set_password(::haxe::ui::util::_Variant::Variant_Impl__obj::toBool(password));
HXLINE( 389)						textfield->removeClass(HX_(":empty",13,28,8d,a0),null(),null());
            					}
            				}
            			}
            			else {
HXLINE( 392)				textfield->removeClass(HX_(":empty",13,28,8d,a0),null(),null());
HXLINE( 393)				textfield->set_password(::haxe::ui::util::_Variant::Variant_Impl__obj::toBool(password));
            			}
            		}
            		else {
HXLINE( 396)			textfield->set_password(::haxe::ui::util::_Variant::Variant_Impl__obj::toBool(password));
HXLINE( 398)			if ((placeholderVisible == true)) {
HXLINE( 399)				textfield->removeClass(HX_(":empty",13,28,8d,a0),null(),null());
            			}
            		}
HXLINE( 403)		textfield->getTextInput()->set_htmlText((HX_("",00,00,00,00) + htmlText));
HXLINE( 404)		{
HXLINE( 404)			bool _hx_tmp2;
HXDLIN( 404)			if (::hx::IsNotNull( textfield->_layout )) {
HXLINE( 404)				_hx_tmp2 = (textfield->_layoutLocked == true);
            			}
            			else {
HXLINE( 404)				_hx_tmp2 = true;
            			}
HXDLIN( 404)			if (!(_hx_tmp2)) {
HXLINE( 404)				textfield->invalidateComponent(HX_("layout",aa,ae,b8,58),false);
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(TextFieldHelper_obj,validateHtmlText,(void))


TextFieldHelper_obj::TextFieldHelper_obj()
{
}

bool TextFieldHelper_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 12:
		if (HX_FIELD_EQ(inName,"validateText") ) { outValue = validateText_dyn(); return true; }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"validateHtmlText") ) { outValue = validateHtmlText_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *TextFieldHelper_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *TextFieldHelper_obj_sStaticStorageInfo = 0;
#endif

::hx::Class TextFieldHelper_obj::__mClass;

static ::String TextFieldHelper_obj_sStaticFields[] = {
	HX_("validateText",63,cc,f9,a0),
	HX_("validateHtmlText",6e,32,91,c8),
	::String(null())
};

void TextFieldHelper_obj::__register()
{
	TextFieldHelper_obj _hx_dummy;
	TextFieldHelper_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.ui.components._TextField.TextFieldHelper",01,86,87,a1);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &TextFieldHelper_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(TextFieldHelper_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< TextFieldHelper_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = TextFieldHelper_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = TextFieldHelper_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace haxe
} // end namespace ui
} // end namespace components
} // end namespace _TextField
