// Generated by Haxe 4.3.3
#ifndef INCLUDED_hx_widgets_TimerEvent
#define INCLUDED_hx_widgets_TimerEvent

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_hx_widgets_Event
#include <hx/widgets/Event.h>
#endif
#ifndef INCLUDED_3fabc4d277dfeb98
#define INCLUDED_3fabc4d277dfeb98
#include "wx/timer.h"
#endif
HX_DECLARE_CLASS2(hx,widgets,Event)
HX_DECLARE_CLASS2(hx,widgets,EvtHandler)
HX_DECLARE_CLASS2(hx,widgets,Object)
HX_DECLARE_CLASS2(hx,widgets,Timer)
HX_DECLARE_CLASS2(hx,widgets,TimerEvent)
HX_DECLARE_CLASS2(hx,widgets,Trackable)

namespace hx{
namespace widgets{


class HXCPP_CLASS_ATTRIBUTES TimerEvent_obj : public  ::hx::widgets::Event_obj
{
	public:
		typedef  ::hx::widgets::Event_obj super;
		typedef TimerEvent_obj OBJ_;
		TimerEvent_obj();

	public:
		enum { _hx_ClassId = 0x36a79114 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="hx.widgets.TimerEvent")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"hx.widgets.TimerEvent"); }
		static ::hx::ObjectPtr< TimerEvent_obj > __new();
		static ::hx::ObjectPtr< TimerEvent_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~TimerEvent_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("TimerEvent",35,32,87,fd); }

		 ::hx::widgets::Timer timer;
		 ::hx::widgets::Timer get_timer();
		::Dynamic get_timer_dyn();

		::cpp::Pointer<  wxTimerEvent > timerEventRef;
		::cpp::Pointer<  wxTimerEvent > get_timerEventRef();
		::Dynamic get_timerEventRef_dyn();

};

} // end namespace hx
} // end namespace widgets

#endif /* INCLUDED_hx_widgets_TimerEvent */ 
