// Generated by Haxe 4.3.1
#ifndef INCLUDED_hx_widgets_TextCtrl
#define INCLUDED_hx_widgets_TextCtrl

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_hx_widgets_Control
#include <hx/widgets/Control.h>
#endif
#ifndef INCLUDED_hx_widgets_TextEntry
#include <hx/widgets/TextEntry.h>
#endif
#ifndef INCLUDED_224ae41206d096c1
#define INCLUDED_224ae41206d096c1
#include "wx/textctrl.h"
#endif
HX_DECLARE_CLASS2(hx,widgets,Control)
HX_DECLARE_CLASS2(hx,widgets,EvtHandler)
HX_DECLARE_CLASS2(hx,widgets,Object)
HX_DECLARE_CLASS2(hx,widgets,Point)
HX_DECLARE_CLASS2(hx,widgets,TextCtrl)
HX_DECLARE_CLASS2(hx,widgets,TextEntry)
HX_DECLARE_CLASS2(hx,widgets,Trackable)
HX_DECLARE_CLASS2(hx,widgets,Window)

namespace hx{
namespace widgets{


class HXCPP_CLASS_ATTRIBUTES TextCtrl_obj : public  ::hx::widgets::Control_obj
{
	public:
		typedef  ::hx::widgets::Control_obj super;
		typedef TextCtrl_obj OBJ_;
		TextCtrl_obj();

	public:
		enum { _hx_ClassId = 0x0f2dbd53 };

		void __construct( ::hx::widgets::Window parent,::String text,::hx::Null< int >  __o_style,::hx::Null< int >  __o_id);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="hx.widgets.TextCtrl")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"hx.widgets.TextCtrl"); }
		static ::hx::ObjectPtr< TextCtrl_obj > __new( ::hx::widgets::Window parent,::String text,::hx::Null< int >  __o_style,::hx::Null< int >  __o_id);
		static ::hx::ObjectPtr< TextCtrl_obj > __alloc(::hx::Ctx *_hx_ctx, ::hx::widgets::Window parent,::String text,::hx::Null< int >  __o_style,::hx::Null< int >  __o_id);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~TextCtrl_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		void *_hx_getInterface(int inHash);
		::String __ToString() const { return HX_("TextCtrl",18,98,75,1e); }

		void appendText(::String value);
		::Dynamic appendText_dyn();

		void autoComplete(::Array< ::String > choices);
		::Dynamic autoComplete_dyn();

		bool canCopy();
		::Dynamic canCopy_dyn();

		bool canCut();
		::Dynamic canCut_dyn();

		bool canPaste();
		::Dynamic canPaste_dyn();

		bool canRedo();
		::Dynamic canRedo_dyn();

		bool canUndo();
		::Dynamic canUndo_dyn();

		::String changeValue(::String value);
		::Dynamic changeValue_dyn();

		void clear();
		::Dynamic clear_dyn();

		void copy();
		::Dynamic copy_dyn();

		void cut();
		::Dynamic cut_dyn();

		void forceUpper();
		::Dynamic forceUpper_dyn();

		int get_insertionPoint();
		::Dynamic get_insertionPoint_dyn();

		int set_insertionPoint(int value);
		::Dynamic set_insertionPoint_dyn();

		 ::hx::widgets::Point get_margins();

		 ::hx::widgets::Point set_margins( ::hx::widgets::Point pt);

		::String getRange(int from,int to);
		::Dynamic getRange_dyn();

		virtual ::String get_value();
		::Dynamic get_value_dyn();

		virtual ::String set_value(::String value);
		::Dynamic set_value_dyn();

		 ::Dynamic get_selection();
		::Dynamic get_selection_dyn();

		 ::Dynamic set_selection( ::Dynamic sel);
		::Dynamic set_selection_dyn();

		::String stringSelection;
		::String get_stringSelection();
		::Dynamic get_stringSelection_dyn();

		bool get_editable();
		::Dynamic get_editable_dyn();

		bool set_editable(bool b);
		::Dynamic set_editable_dyn();

		bool isEmpty();
		::Dynamic isEmpty_dyn();

		void paste();
		::Dynamic paste_dyn();

		void redo();
		::Dynamic redo_dyn();

		void remove(int from,int to);
		::Dynamic remove_dyn();

		void replace(int from,int to,::String value);
		::Dynamic replace_dyn();

		void selectAll();
		::Dynamic selectAll_dyn();

		void selectNone();
		::Dynamic selectNone_dyn();

		::String get_hint();
		::Dynamic get_hint_dyn();

		::String set_hint(::String value);
		::Dynamic set_hint_dyn();

		int maxLength;
		int set_maxLength(int len);
		::Dynamic set_maxLength_dyn();

		void undo();
		::Dynamic undo_dyn();

		void writeText(::String value);
		::Dynamic writeText_dyn();

		::cpp::Pointer<  wxTextCtrl > textCtrlRef;
		::cpp::Pointer<  wxTextCtrl > get_textCtrlRef();
		::Dynamic get_textCtrlRef_dyn();

};

} // end namespace hx
} // end namespace widgets

#endif /* INCLUDED_hx_widgets_TextCtrl */ 
